[default]
LAZY_LOADING=true
DISTRIBUTED = true
CACHE_DIR="./.caches"
GPU_DEVICES_ID = [0, 1, 2, 3]
CHAT_MODEL_NAME = "Qwen/Qwen2.5-14B-Instruct"
MAX_NEW_TOKEN_CHAT_MODEL = 512
ENABLE_VISION_MODEL = false
VISION_MODEL_NAME = "Qwen/Qwen2-VL-7B-Instruct"
MAX_NEW_TOKEN_VISION_MODEL = 128